name: Security
iam_by_principals:
  $iam_principals:service_accounts/iac-0/iac-security-rw:
  - roles/logging.admin
  - roles/owner
  - roles/resourcemanager.folderAdmin
  - roles/resourcemanager.projectCreator
  - roles/resourcemanager.tagUser
  $iam_principals:service_accounts/iac-0/iac-security-ro:
  - roles/resourcemanager.folderViewer
  - roles/resourcemanager.tagViewer
  - roles/viewer
