project_id: $project_ids:net-core-0
delete_default_routes_on_create: true
nat_config:
  nat-vpc-hub-us-central1:
    region: us-central1
  nat-vpc-hub-us-west2:
    region: us-west2
routes:
  default-route:
    dest_range: 0.0.0.0/0
    next_hop: default-internet-gateway
